version: '3.7'

services:
  web:
    build: .
    command: >
      bash -c "python data.py -docker && 
      python manage.py run -h 0.0.0.0"
    volumes:
      - .:/usr/src/app/
    environment:
      - GOOGLE_CHROME_SHIM=/app/.apt/usr/bin/google-chrome
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=covid

volumes:
  postgres_data:

